ITEM_MAPPING = {
	-- staff
	[1] = {Staff, "toggle"},
	[2] = {FireBlaster, "toggle"},
	[3] = {RocketBoost, "toggle"},
	[4] = {FreezeBlast, "toggle"},
	[5] = {GroundQuake, "toggle"},
	[6] = {Disguise, "toggle"},
	-- tricky
	[10] = {Tricky, "progressive"},
	-- planet
	[50] = {DinoPlanetAccess, "toggle"},
	[51] = {DarkIceAccess, "toggle"},
	-- [52] = {CloudRunnerFortress, "toggle"},
	-- [53] = {WalledCity, "toggle"},
	-- [54] = {DragonRock, "toggle"},
	-- inventory
	[100] = {ScarabBag, "progressive"},
	[101] = {BombPlant, "toggle"},
	[102] = {AlpineSHW, "consumable"},
	[103] = {WhiteGrubTub, "consumable"},
	[104] = {GateKey, "toggle"},
	[105] = {EntranceCog, "toggle"},
	[106] = {AlpineDIM, "consumable"},
	[107] = {SharpClawCogs, "consumable"},
	[110] = {DinosaurHorn, "toggle"},
	-- [111] = {SilverKey, "toggle"},
	-- [112] = {DimGoldKey, "toggle"},
	[113] = {FireSpellstone1, "toggle"},
	[114] = {MoonPassKey, "toggle"},
	[115] = {MoonSeed, "toggle"},
	[116] = {KrazoaSpirit2, "toggle"},
	[117] = {GoldBar, "consumable"},
	[118] = {PowerKey, "toggle"},
	[119] = {RedCrystal, "toggle"},
	[120] = {GreenCrystal, "toggle"},
	[121] = {BlueCrystal, "toggle"},
	[122] = {CloudRunnerFlute, "toggle"},
	-- shop
	[200] = {RockCandy, "toggle"},
	-- [201] = {HiTechDisplay, "toggle"},
	[204] = {FireFlyLantern, "toggle"},
	-- [205] = {SnowhornArtifact, "toggle"},
}