Tracker:AddLocations("locations/world_map.jsonc")
Tracker:AddLocations("locations/thorntail_hollow.jsonc")
Tracker:AddLocations("locations/snowhorn_wastes.jsonc")
Tracker:AddLocations("locations/lightfoot_village.jsonc")
Tracker:AddLocations("locations/moon_mountain_pass.jsonc")
Tracker:AddLocations("locations/darkice_mines.jsonc")
