Tracker:AddLocations("locations/world_map.jsonc")
Tracker:AddLocations("locations/thorntail_hollow.jsonc")
Tracker:AddLocations("locations/ice_mountain.jsonc")
Tracker:AddLocations("locations/snowhorn_wastes.jsonc")
Tracker:AddLocations("locations/lightfoot_village.jsonc")
Tracker:AddLocations("locations/moon_mountain.jsonc")
