-- Staff
Staff = "staff"
FireBlaster = "fireBlaster"
RocketBoost = "rocketBoost"
FreezeBlast = "freezeBlast"
GroundQuake = "groundQuake"
SuperQuake = "superQuake"
Disguise = "disguise"
-- Tricky
Tricky = "tricky"
Find = "find"
Stay = "stay"
Flame = "flame"
-- Planet
DinoPlanetAccess = "dinoPlanetAccess"
DarkIceAccess = "darkIceAccess"
CloudRunnerAccess = "cloudRunnerAccess"
-- Inventory
ScarabBag = "scarabPockets"
SmallScarabBag = "scarabSmall"
MediumScarabBag = "scarabMedium"
LargeScarabBag = "scarabLarge"
BombPlant = "bombPlant"
AlpineSHW = "alpineSHW"
AlpineDIM = "alpineDIM"
WhiteGrubTub = "whiteGrubTub"
GateKey = "gateKey"
EntranceCog = "entranceCog"
SharpClawCogs = "sharpClawCogs"
DinosaurHorn = "dinosaurHorn"
FireSpellstone1 = "fireSpellstone1"
MoonPassKey = "moonPassKey"
MoonSeed = "moonSeed"
KrazoaSpirit2 = "krazoa2"
RockCandy = "rockCandy"
FireFlyLantern = "fireFlyLantern"
HiTechDisplay = "hiTechDisplay"
GoldBar = "goldBar"
PowerKey = "powerKey"
RedCrystal = "crystalRed"
GreenCrystal = "crystalGreen"
BlueCrystal = "crystalBlue"
CloudRunnerFlute = "cloudRunnerFlute"
-- Settings
ShopSetting = "shopSetting"
ShopEnabled = "shopEnabled"
ShopMaps = "shopMaps"
ShopNoMaps = "shopNoMaps"
ShopDisabled = "shopDisabled"
PlantShuffle = "plantShuffle"
PlantShuffleOn = "plantShuffleOn"
PlantShuffleOff = "plantShuffleOff"
